version: '2'
services:
  mongo:
    image: mongo:2.6.12
    container_name: mongodb
    
  tomcat-epcis:
    image: tomcat:8.0-jre8
    links:
      - mongo
    ports:
      - 8080:8080
    volumes:
      - ./epcis/epcis.war:/usr/local/tomcat/webapps/epcis.war
